experiment:
  project: "finetuner"
  tag: "cifar100_res50_PretrainI21k"
  strategy: "OnlyFinetuneStrategy"
  
output_dir: "/home/vmagent/app/data/model"
train_epochs: 1
enable_ipex: True

### dataset
data_set: "cifar100"
data_path:  "/home/vmagent/app/data/dataset/cifar"
num_workers: 4
input_size: 112

### model
model_type: "resnet50"

## finetuner
finetuner:
    type: "Basic"
    pretrain: '/home/vmagent/app/data/pretrained/resnet50_miil_21k.pth'
    pretrained_num_classes: 11221
    finetuned_lr: 0.00445
    frozen: False

## optimizer
optimizer: "SGD"
learning_rate: 0.00753
weight_decay: 0.00115
momentum: 0.9

### scheduler
lr_scheduler: "CosineAnnealingLR"
lr_scheduler_config:
    T_max: 200

### early stop
early_stop: "EarlyStopping"
early_stop_config:
    tolerance_epoch: 15
