name: Integration Test Workload RNNT

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/integration_test_workload_rnnt.yml'
    - 'conf/e2eaiok_defaults_rnnt_example.conf'
    - 'demo/builtin/rnnt/**'
    - 'Dockerfile-ubuntu18.04/DockerfilePytorch110'
    - 'e2eAIOK/SDA/**'
    - 'e2eAIOK/common/**'
    - 'e2eAIOK/dataloader/**'
    - 'e2eAIOK/utils/**'
    - 'modelzoo/rnnt/**'
    - 'tests/cicd/conf/**'
    - 'tests/cicd/src/**'
    - 'tests/cicd/test_*.bats'
    - 'tests/cicd/Jenkinsfile*'
    - 'tests/cicd/jenkins_rnnt_test*.sh'

jobs:
  integration_test:
    name: Integration Test Workload RNNT
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Docker
      run: |
        cd Dockerfile-ubuntu18.04 && docker build -t e2eaiok-pytorch110 . -f DockerfilePytorch110 && cd .. && yes | docker container prune && yes | docker image prune

    - name: Test RNNT
      run: |
        if [[ $(docker ps -q --filter "name=test-workload-rnnt" | wc -l) -ne 0 ]]; then docker ps -q --filter "name=test-workload-rnnt" | grep -q . && docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q); fi
        cd modelzoo/rnnt/pytorch && bash patch_rnnt.sh && cd ../../..
        docker run --rm --name test-workload-rnnt --privileged --network host --device=/dev/dri -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/e2eaiok -w /home/vmagent/app/ e2eaiok-pytorch110 /bin/bash -c "USE_SIGOPT=0 . /home/vmagent/app/e2eaiok/tests/cicd/jenkins_rnnt_test.sh"