name: Integration Test Workload MiniGo

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/integration_test_workload_minigo.yml'
    - 'conf/e2eaiok_defaults_minigo_example.conf'
    - 'demo/builtin/minigo/**'
    - 'e2eAIOK/SDA/**'
    - 'e2eAIOK/common/**'
    - 'e2eAIOK/dataloader/**'
    - 'e2eAIOK/utils/**'
    - 'modelzoo/minigo/**'
    - 'tests/cicd/conf/**'
    - 'tests/cicd/src/**'
    - 'tests/cicd/test_*.bats'
    - 'tests/cicd/Jenkinsfile*'
    - 'tests/cicd/jenkins_minigo_test*.sh'

jobs:
  integration_test:
    name: Integration Test Workload MiniGo
    runs-on: sr612
    steps:
    - name: Cleanup for MiniGo
      run: |
        rm -rf /tmp/golden_chunks || true
        rm -rf /tmp/golden_chunks_tmp || true
        rm -rf /tmp/selfplay || true
        rm -rf /tmp/selfplay_local/ || true
        rm -rf /tmp/signal || true
        pkill -f ml_perf || true

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Test MiniGo
      run: |
        cd modelzoo/minigo && bash patch_minigo.sh && cd ../..
        USE_SIGOPT=0 bash tests/cicd/jenkins_minigo_test.sh