name: Performance test AutoFE

on:
  pull_request:
    types: [labeled]
    branches:
    - RecDP_v2.0

jobs:
  perf-test:
    name: Performance test AutoFE
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker
      run: |
        cd RecDP && cd Dockerfile && docker build -t pyrecdp-test-env . -f DockerfileUbuntu --build-arg https_proxy=${https_proxy} && cd .. && yes | docker container prune && yes | docker image prune 

    - name: RUN Unittests
      run: |
        cd RecDP && docker run --rm --name pyrecdp-autofe-performance-test --shm-size=100g --privileged --network host --device=/dev/dri -v /mnt/DP_disk1/dataset:/home/vmagent/app/dataset -v `pwd`:/home/vmagent/app/ -w /home/vmagent/app/ pyrecdp-test-env /bin/bash -c "sh tests/cicd/bashrun_performance_test_autofe.sh"